server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296/
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**