hibernate:
    format_sql: true
    show_sql: true
server:
    port: 8082
spring:
    application:
        name: USER-SERVICE
    zipkin:
        base-url: http://localhost:9411
    config:
        import: configserver:http://localhost:9296/
    datasource:
        password: pwd703532
        url: jdbc:postgresql://localhost:5432/userservice
        username: postgres
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
